# Generated by Django 3.2.8 on 2021-10-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211031_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.TextField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(default='tanay@gmail.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(default='Male', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default='', max_length=255, unique=True),
        ),
    ]
