# Generated by Django 3.2.8 on 2021-11-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
