# Generated by Django 3.2.8 on 2021-11-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField(default='')),
                ('COVER_IMAGE', models.FileField(upload_to='MEDIA')),
                ('DOC', models.FileField(upload_to='MEDIA')),
            ],
        ),
    ]
