# Generated by Django 3.2.8 on 2021-11-03 07:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='COVER_IMAGE',
            field=models.FileField(upload_to=main.models.get_new_dir),
        ),
        migrations.AlterField(
            model_name='book',
            name='DOC',
            field=models.FileField(upload_to=main.models.get_new_dir),
        ),
    ]
