# Generated by Django 3.2.8 on 2021-11-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211103_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='COVER_IMAGE',
            field=models.FileField(upload_to='MEDIA/0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='DOC',
            field=models.FileField(upload_to='MEDIA/0'),
        ),
    ]
