# Generated by Django 3.2.8 on 2021-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211104_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='COVER_IMAGE',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.TextField(default=''),
        ),
    ]
