# Generated by Django 3.2.9 on 2021-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211104_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='COVER',
            field=models.FileField(default=-1, upload_to='MEDIA/0'),
            preserve_default=False,
        ),
    ]
