# Generated by Django 4.0.3 on 2022-04-14 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='User_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_ids',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
